config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true, length: { in: 1..10 }
  validates :softness, presence: true, length: { in: 1..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.xml { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to kitten_path(@kitten), notice: "Kitten succesfully created!"
    else
      flash[:alert] = "Fix your errors!"
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    
    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten), notice: "Kitten succesfully updated!"
    else
      flash[:alert] = "Fix your errors!"
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to kittens_path, notice: "Kitten succesfully deleted!"
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<% if @kitten.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @kitten.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @kitten, local: true do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %><BR>
  <%= f.label :age, "Age:" %>
  <%= f.number_field :age %><BR>
  <%= f.label :cuteness, "Cuteness (1-10):" %>
  <%= f.number_field :cuteness, in: 1..10 %><BR>
  <%= f.label :softness, "Softness (1-10):" %>
  <%= f.number_field :softness, in: 1..10 %><BR>
  <%= f.submit "Submit" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render partial: 'form' %>

<%= link_to "Delete Kitten", kitten_path(@kitten), method: :delete, data: {confirm: "Really delete this kitten?"} %> || 
<%= link_to "Back to All", kittens_path %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten_path(kitten)%> || <%= link_to "Edit Kitten", edit_kitten_path(kitten) %> || <%= link_to "Delete Kitten", kitten_path(kitten), method: :delete, data: {confirm: "Really delete this kitten?"} %>
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create New Kitten</h1>

<%= render partial: 'form' %>

app/views/kittens/show.html.erb
<h1>Details for <%= @kitten.name %></h1>

<p><strong>Name:</strong> <%= @kitten.name %></p>
<p><strong>Age:</strong> <%= @kitten.age %></p>
<p><strong>Cuteness:</strong> <%= @kitten.cuteness %></p>
<p><strong>Softness:</strong> <%= @kitten.softness %></p>

<%= link_to "Edit Kitten", edit_kitten_path(@kitten) %> || 
<%= link_to "Delete Kitten", kitten_path(@kitten), method: :delete, data: {confirm: "Really delete this kitten?"} %> || 
<%= link_to "Back to All", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="navbar">
      <%= link_to "New Kitten", new_kitten_path %> || 
      <%= link_to "All Kittens", kittens_path %>
    </div>

    <%= yield %>
  </body>
</html>